#!/bin/bash
#
# When run in the repository root directory, produces `pkg/util/version.go`.
#

if [ -d .git ]; then
    # best option: use git-describe
    VERSION="$(git describe --tags --dirty)"
else
    # second-best option: when running inside an unpacked release tarball, the
    # root directory's name indicates the version, e.g. "swift-http-import-1.2"
    root_basename="$(basename "$(readlink -f .)")"
    if [[ $root_basename =~ swift-http-import-* ]]; then
        VERSION="${root_basename/swift-http-import-/}"
    else
        echo "Cannot determine application version. The root directory basename should look like 'swift-http-import-1.2.3', but actually is '$root_basename'." >&2
        exit 1
    fi
fi

cat > pkg/util/version.go <<-EOF
//WARNING: this file is autogenerated by util/find_version.sh
package util
const Version = "$VERSION"
EOF
