swift:
  auth_url: https://my.keystone.local:5000/v3
  application_credential_id: 80e810bf385949ae8f0e251f90269515
  application_credential_secret: eixohMoo1on5ohng

jobs:
  - from:
      url: http://de.archive.ubuntu.com/ubuntu/
    to:
      container: mirror
      object_prefix: ubuntu-repos
